package es.propio.modeladoInfo;

/**
 * @author i3casa
 * 
 */
public enum ParametroNombre {

	NUMEROJORNADA("NUMEROJORNADA"), JUEGA_EN_CASA("JUEGA_EN_CASA"), JUEGA_FUERA(
			"JUEGA_FUERA"), NUMERO_UNOS_ANTERIORES("NUMERO_UNOS_ANTERIORES"), NUMERO_EQUIS_ANTERIORES(
			"NUMERO_EQUIS_ANTERIORES"), NUMERO_DOSES_ANTERIORES(
			"NUMERO_DOSES_ANTERIORES"), GOLESENCASAAFAVOR("GOLESENCASAAFAVOR"), GOLESENCASAENCONTRA(
			"GOLESENCASAENCONTRA"), GOLESFUERAAFAVOR("GOLESFUERAAFAVOR"), GOLESFUERAENCONTRA(
			"GOLESFUERAENCONTRA"), GOLESTOTALESAFAVOR("GOLESTOTALESAFAVOR"), GOLESTOTALESENCONTRA(
			"GOLESTOTALESENCONTRA"), PUNTOSSIMPLES("PUNTOSSIMPLES"), GANADOS(
			"GANADOS"), EMPATADOS("EMPATADOS"), PERDIDOS("PERDIDOS"), PUNTOSNORMALES(
			"PUNTOSNORMALES"), DIFERENCIADEGOLESENCONTRA(
			"DIFERENCIADEGOLESENCONTRA"), DIFERENCIADEGOLESAFAVOR(
			"DIFERENCIADEGOLESAFAVOR"), POSICION_EN_CLASIFICACION(
			"POSICION_EN_CLASIFICACION"), PARTIDOS_JUGADOS("PARTIDOS_JUGADOS"), PARTIDOS_GANADOS(
			"PARTIDOS_GANADOS"), PARTIDOS_EMPATADOS("PARTIDOS_EMPATADOS"), PARTIDOS_PERDIDOS(
			"PARTIDOS_PERDIDOS"), GOLES_A_FAVOR("GOLES_A_FAVOR"), GOLES_EN_CONTRA(
			"GOLES_EN_CONTRA"), REMATES_EN_CONTRA("REMATES_EN_CONTRA"), JUGADORES_UTILIZADOS(
			"JUGADORES_UTILIZADOS"), PARADAS_DEL_PORTERO("PARADAS_DEL_PORTERO"), AF_BALON_PARADO(
			"AF_BALON_PARADO"), AF_CABEZA("AF_CABEZA"), AF_FALTA_DIRECTA(
			"AF_FALTA_DIRECTA"), AF_JUGADA_COLECTIVA("AF_JUGADA_COLECTIVA"), AF_JUGADA_INDIVIDUAL(
			"AF_JUGADA_INDIVIDUAL"), AF_PENALTY("AF_PENALTY"), AF_PIE_IZQUIERDO(
			"AF_PIE_IZQUIERDO"), AF_PIE_DERECHO("AF_PIE_DERECHO"), EN_CONTRA(
			"EN_CONTRA"), GC_CABEZA("GC_CABEZA"), GC_PENALTY("GC_PENALTY"), GOLES_TITULAR(
			"GOLES_TITULAR"), GOLES_SUPLENTES("GOLES_SUPLENTES"), REMATES_FAVOR(
			"REMATES_FAVOR"), RF_BALON_PARADO("RF_BALON_PARADO"), RF_CABEZA(
			"RF_CABEZA"), RF_FUERA("RF_FUERA"), RF_JUGADA_COLECTIVA(
			"RF_JUGADA_COLECTIVA"), RF_JUGADA_INDIVIDUAL("RF_JUGADA_INDIVIDUAL"), RF_PENALTY(
			"RF_PENALTY"), RF_PIE_IZQUIERDO("RF_PIE_IZQUIERDO"), RF_PIE_DERECHO(
			"RF_PIE_DERECHO"), RF_POSTE("RF_POSTE"), RF_PORTERIA("RF_PORTERIA"),

	RC_CABEZA("RC_CABEZA"), RC_FUERA("RC_FUERA"), RC_PORTERIA("RC_PORTERIA"), RC_POSTE(
			"RC_POSTE"), TARJETAS_AMARILLAS("TARJETAS_AMARILLAS"), TARJETAS_ROJAS(
			"TARJETAS_ROJAS"),

	INVALIDO("-");

	private String nombre;

	private ParametroNombre(String nombre) {
		this.nombre = nombre;
	}

	@Override
	public String toString() {
		return name();
	}

	public boolean isParametroComunDeEquipo() {
		boolean esComun = false;
		if (this.equals(POSICION_EN_CLASIFICACION)
				|| this.equals(PARTIDOS_JUGADOS)
				|| this.equals(PARTIDOS_GANADOS)
				|| this.equals(PARTIDOS_EMPATADOS)
				|| this.equals(PARTIDOS_PERDIDOS) || this.equals(GOLES_A_FAVOR)
				|| this.equals(GOLES_EN_CONTRA)) {
			esComun = true;
		}

		return esComun;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int compareTo(String anotherString) {
		return nombre.compareTo(anotherString);
	}

}
